# 用户凭据配置
[credentials]
admin = "admin123"
Baptiste = "123456"
Vincent = "123456"
Kaiyuan = "123456"
user2 = "user456"

# 用户角色配置（用于区分管理员和普通用户）
[roles]
admin = "admin"
doctor1 = "admin"
doctor2 = "admin"
Kaiyuan = "user"
user2 = "user" 
